from openworkstation import robot2

from plateDimensions.well_plate_96  import *
from moduleSensor import lower_sensor_into_plate, lower_sensor_above_plate


# from plateDimensions.well_plate  import


def getModuleposition():
    moduleposition = {}
    # module positions
    # currently, module sensor position is written for 96-well plates
    # x position is in line with raw A
    moduleposition['moduleSensor'] = 'G0 X116'
    moduleposition['moduleLifter'] = 'G0 X5 Y3 Z3'
    moduleposition['lidHolder'] = 'G0 X100 Y3 Z3'
    # make sure that cups are at waiting positiong
    return(moduleposition)


moduleposition = getModuleposition()

# define time for well measurement performed by sensor
time_per_measurement = 5


def move_to_moduleSensor():
    robot2._driver.send_command('G90')
    robot2._driver.send_command('G0 F500')
    robot2._driver.send_command(moduleposition['moduleSensor'])
    sleep(1)


def move_to_moduleLifter():
    robot2._driver.send_command('G90')
    robot2._driver.send_command('G0 F500')
    robot2._driver.send_command(moduleposition['moduleLifter'])
    sleep(1)


def move_to_lidHolder():
    robot2._driver.send_command('G90')
    robot2._driver.send_command('G0 F500')
    robot2._driver.send_command(moduleposition['lidHolder'])
    sleep(1)

# measure 96 well plate without external wells
# profile takes 225 seconds, add 10 seconds for synchronization
time_per_measurement = 236.5
initial = 5
def measure_96plate_internal():
    #sleep(initial)
    move_to_plate96_A1()
    sleep(time_per_measurement)
    move_to_plate96_B1()
    sleep(time_per_measurement)
    # column 2
    move_to_plate96_B2()
    sleep(time_per_measurement)
    move_to_plate96_C2()
    sleep(time_per_measurement)
    move_to_plate96_D2()
    sleep(time_per_measurement)
    move_to_plate96_E2()
    sleep(time_per_measurement)
    move_to_plate96_F2()
    sleep(time_per_measurement)
    move_to_plate96_G2()
    sleep(time_per_measurement)
    # column 3
    move_to_plate96_G3()
    sleep(time_per_measurement)
    move_to_plate96_F3()
    sleep(time_per_measurement)
    move_to_plate96_E3()
    sleep(time_per_measurement)
    move_to_plate96_D3()
    sleep(time_per_measurement)
    move_to_plate96_C3()
    sleep(time_per_measurement)
    move_to_plate96_B3()
    sleep(time_per_measurement)
    # column 4
    move_to_plate96_B4()
    sleep(time_per_measurement)
    move_to_plate96_C4()
    sleep(time_per_measurement)
    move_to_plate96_D4()
    sleep(time_per_measurement)
    move_to_plate96_E4()
    sleep(time_per_measurement)
    move_to_plate96_F4()
    sleep(time_per_measurement)
    move_to_plate96_G4()
    sleep(time_per_measurement)
    # column 5
    move_to_plate96_G5()
    sleep(time_per_measurement)
    move_to_plate96_F5()
    sleep(time_per_measurement)
    move_to_plate96_E5()
    sleep(time_per_measurement)
    move_to_plate96_D5()
    sleep(time_per_measurement)
    move_to_plate96_C5()
    sleep(time_per_measurement)
    move_to_plate96_B5()
    sleep(time_per_measurement)
    # column 6
    move_to_plate96_B6()
    sleep(time_per_measurement)
    move_to_plate96_C6()
    sleep(time_per_measurement)
    move_to_plate96_D6()
    sleep(time_per_measurement)
    move_to_plate96_E6()
    sleep(time_per_measurement)
    move_to_plate96_F6()
    sleep(time_per_measurement)
    move_to_plate96_G6()
    sleep(time_per_measurement)
    # column 7
    move_to_plate96_G7()
    sleep(time_per_measurement)
    move_to_plate96_F7()
    sleep(time_per_measurement)
    move_to_plate96_E7()
    sleep(time_per_measurement)
    move_to_plate96_D7()
    sleep(time_per_measurement)
    move_to_plate96_C7()
    sleep(time_per_measurement)
    move_to_plate96_B7()
    sleep(time_per_measurement)
    # column 8
    move_to_plate96_B8()
    sleep(time_per_measurement)
    move_to_plate96_C8()
    sleep(time_per_measurement)
    move_to_plate96_D8()
    sleep(time_per_measurement)
    move_to_plate96_E8()
    sleep(time_per_measurement)
    move_to_plate96_F8()
    sleep(time_per_measurement)
    move_to_plate96_G8()
    sleep(time_per_measurement)
    # column 9
    move_to_plate96_G9()
    sleep(time_per_measurement)
    move_to_plate96_F9()
    sleep(time_per_measurement)
    move_to_plate96_E9()
    sleep(time_per_measurement)
    move_to_plate96_D9()
    sleep(time_per_measurement)
    move_to_plate96_C9()
    sleep(time_per_measurement)
    move_to_plate96_B9()
    sleep(time_per_measurement)
    # column 10
    move_to_plate96_B10()
    sleep(time_per_measurement)
    move_to_plate96_C10()
    sleep(time_per_measurement)
    move_to_plate96_D10()
    sleep(time_per_measurement)
    move_to_plate96_E10()
    sleep(time_per_measurement)
    move_to_plate96_F10()
    sleep(time_per_measurement)
    move_to_plate96_G10()
    sleep(time_per_measurement)
    # column 11
    move_to_plate96_G11()
    sleep(time_per_measurement)
    move_to_plate96_F11()
    sleep(time_per_measurement)
    move_to_plate96_E11()
    sleep(time_per_measurement)
    move_to_plate96_D11()
    sleep(time_per_measurement)
    move_to_plate96_C11()
    sleep(time_per_measurement)
    move_to_plate96_B11()
    sleep(time_per_measurement)
    sleep(time_per_measurement)


# presens: wait 31 sec
# measure entire 96 well plate
# time_per_measurement = 226.2
def measure_96plate():
    move_to_plate96_A1()
    robot2._driver.send_command('G4 S1')
    # normal: 224
    sleep(224)
    move_to_plate96_A2()
    sleep(time_per_measurement)
    move_to_plate96_A3()
    sleep(time_per_measurement)
    move_to_plate96_B12()
    sleep(time_per_measurement)
    move_to_plate96_B11()
    sleep(time_per_measurement)
    move_to_plate96_B10()
    sleep(time_per_measurement)
    move_to_plate96_B9()
    sleep(time_per_measurement)
    move_to_plate96_B8()
    sleep(time_per_measurement)
    move_to_plate96_B7()
    sleep(time_per_measurement)
    move_to_plate96_C1()
    sleep(time_per_measurement)
    move_to_plate96_C2()
    sleep(time_per_measurement)
    move_to_plate96_C3()
    sleep(time_per_measurement)
    move_to_plate96_C4()
    sleep(time_per_measurement)
    move_to_plate96_C5()
    sleep(time_per_measurement)
    move_to_plate96_C6()
    sleep(time_per_measurement)
    move_to_plate96_C7()
    sleep(time_per_measurement)
    move_to_plate96_C8()
    sleep(time_per_measurement)
    move_to_plate96_C9()
    sleep(time_per_measurement)
    move_to_plate96_C10()
    sleep(time_per_measurement)
    move_to_plate96_C11()
    sleep(time_per_measurement)
    move_to_plate96_C12()
    sleep(time_per_measurement)
    move_to_plate96_D12()
    sleep(time_per_measurement)
    move_to_plate96_D11()
    sleep(time_per_measurement)
    move_to_plate96_D10()
    sleep(time_per_measurement)
    move_to_plate96_D9()
    sleep(time_per_measurement)
    move_to_plate96_D8()
    sleep(time_per_measurement)
    move_to_plate96_D7()
    sleep(time_per_measurement)
    move_to_plate96_D6()
    sleep(time_per_measurement)
    move_to_plate96_D5()
    sleep(time_per_measurement)
    move_to_plate96_D4()
    sleep(time_per_measurement)
    move_to_plate96_D3()
    sleep(time_per_measurement)
    move_to_plate96_D2()
    sleep(time_per_measurement)
    move_to_plate96_D1()
    sleep(time_per_measurement)
    move_to_plate96_E1()
    sleep(time_per_measurement)
    move_to_plate96_E2()
    sleep(time_per_measurement)
    move_to_plate96_E3()
    sleep(time_per_measurement)
    move_to_plate96_E4()
    sleep(time_per_measurement)
    move_to_plate96_E5()
    sleep(time_per_measurement)
    move_to_plate96_E6()
    sleep(time_per_measurement)
    move_to_plate96_E7()
    sleep(time_per_measurement)
    move_to_plate96_E8()
    sleep(time_per_measurement)
    move_to_plate96_E9()
    sleep(time_per_measurement)
    move_to_plate96_E10()
    sleep(time_per_measurement)
    move_to_plate96_E11()
    sleep(time_per_measurement)
    move_to_plate96_E12()
    sleep(time_per_measurement)



'''
# entire 96 well plate
def measure_96plate():
    move_to_plate96_A1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_A12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_B1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_C12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_D1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_E12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_F1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G1()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_G12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H12()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H11()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H10()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H9()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H8()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H7()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H6()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H5()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H4()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H3()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H2()
    robot2._driver.send_command('G4 S131.9')
    move_to_plate96_H1()
    robot2._driver.send_command('G4 S131.9')
'''
